import {
  ArrowUpDown,
  Bath,
  Bed,
  Bell,
  Camera,
  Car,
  ChefHat,
  Coffee,
  Check,
  Droplet,
  Droplets,
  DoorOpen,
  Dumbbell,
  Flame,
  FlameKindling,
  HeartPulse,
  Laptop,
  Mountain,
  PawPrint,
  PlugZap,
  Shirt,
  Siren,
  Snowflake,
  Trees,
  Tv,
  Umbrella,
  Utensils,
  Waves,
  WashingMachine,
  Wifi,
  Wind,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  wifi: Wifi,
  utensils: Utensils,
  "washing-machine": WashingMachine,
  snowflake: Snowflake,
  flame: Flame,
  car: Car,
  tv: Tv,
  wind: Wind,
  shirt: Shirt,
  laptop: Laptop,
  droplet: Droplet,
  bed: Bed,
  waves: Waves,
  bath: Bath,
  trees: Trees,
  "door-open": DoorOpen,
  dumbbell: Dumbbell,
  "arrow-up-down": ArrowUpDown,
  coffee: Coffee,
  "paw-print": PawPrint,
  "plug-zap": PlugZap,
  umbrella: Umbrella,
  droplets: Droplets,
  mountain: Mountain,
  "chef-hat": ChefHat,
  bell: Bell,
  siren: Siren,
  "heart-pulse": HeartPulse,
  "flame-kindling": FlameKindling,
  camera: Camera,
};

/** Icon for an amenity's `icon_key` (falls back to a check mark). */
export function AmenityIcon({ name, size = 24, className }: { name: string; size?: number; className?: string }) {
  const Icon = ICONS[name] ?? Check;
  return <Icon size={size} strokeWidth={1.5} className={className} />;
}
